---
title: 'Lecture #12'
author: "Ashley Kang"
date: "10/11/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))


```

```{r}
library(rvest)
library(httr)
```

## Scraping Table

First get the HTML

```{r url_HTML}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```

Get the tables from the HTML
```{r tables_HTML}
drug_use_xml %>%
  html_nodes(css = "table") %>% 
      # We have something that looks like piece of HTML code
      # We have things like table but we have 15 of them (we have tables 1 - 15)
      # But now we have too much stuff
  .[[1]] %>% # adding "list" - [[1]] give me first element (table)
      # we see "table 1, marijuana use in past year" - we have right thing
  html_table() %>%  # converting html code into table
      # View looks almost right
  slice(-1) %>% 
      # only case we use slice - bad function; slice lets us access rows of dataset by   
      # number
      # we don't want to filter rows by row # just in case we change and add data later
      # prefer to use filter
  as_tibble()

# data isn't tidy yet... BUT we have data inside R
```

## Learning Assessment #1
```{r learning_assessment_1}
nyc_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table(header = TRUE) # header = TRUE = first row is column names
```

## Harry Potter

Let's get some Potter data! 
```{r hp_saga}
hpsaga_html = read_html("https://www.imdb.com/list/ls000630791/")
# getting title and how much money each movie made but information doesn't exist inside
# table 

titles = hpsaga_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  html_text() # looks more like text than table

money = hpsaga_html %>% 
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

hpsaga_df = tibble(
  title = titles,
  gross_rev = money
)
```

Learning Assessment #2

```{r learning_assessment_2}
nd_review_html = read_html("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1")

review_title = nd_review_html %>% 
  html_nodes(css = "#cm_cr-review_list .review-title") %>% 
  html_text()

review_star = nd_review_html %>% 
  html_nodes(css = "#cm_cr-review_list .review-rating") %>% 
  html_text

review_text = nd_review_html %>% 
  html_nodes(css = ".review-text") %>% 
  html_text

nd_df = tibble(
  title = review_title,
  rating = review_star,
  text = review_text
)
```

## NYC Data - API

Get the water data (API)

```{r nyc_data}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed") # retrieving contents as parsed into R object
```


AS JSON

```{r nyc_data_json}
nyc_water_json = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>% # when extracting text, we can tell when row ends and begins
  jsonlite::fromJSON() %>% # convert from json to something better and parses
  as_tibble()

# json = coming up with a structured way to get information
```


## BRFSS Data

```{r brfss_data}
brfss_smart2010 = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

